#include factionsv3
#include buttonsv2
#include factionboardxml
#include scenarios

chosen_faction = nil

UIASSETS = {
    {
        name = "box-art",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791955263/F669EAAAE073188F7C34FD723B6C66F488338C11/"
    },
    {
        name = "marquise-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791948574/E31DB0846BBD3D08BE3606665FBD724769B6AD47/"
    },
    {
        name = "eyrie-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791947659/183DFFE14E18813FC26E7E5B5F208628A9768912/"
    },
    {
        name = "alliance-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791954955/B7B3C484B6899398F07AFD3D9A10668D46FC2078/"
    },
    {
        name = "vagabond-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791951084/F81EDE1A0756A464C4677F797FE8FD80C42C3AAF/"
    },
    {
        name = "riverfolk-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791949530/BF546C3DB797C09F567273A13052A8639C20AB82/"
    },
    {
        name = "lizard-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791946644/E132B1A7FEEADADC69E807F60807C4A1FC019F24/"
    },
    {
        name = "corvid-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791946168/7A28C4D3D38BA672E26C1B2469A56E656FC83B62/"
    },
    {
        name = "underground-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791946915/AC90F31B99BB4D243370698B9856A013FCB07D8E/"
    },
    {
        name = "mech-marq2-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791949178/081FDF628B9B798822F76634B01B73C6DD58BA78/"
    },
    {
        name = "electric-eyrie",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791947395/79331F94AA2D083589EEDE49117056238648EC42/"
    },
    {
        name = "automated-alliance",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791945457/E61C3BDDCF847A76E242CC170E5C81EB104AD138/"
    },
    {
        name = "vagabot",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791954681/CCD815BB28FCAE9077D11F3B9390C0CC1A051DEA/"
    },
    {
        name = "clockwork-cult",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791945932/A643431C3BB2BB184A52FA91988B50CF9A99CCC8/"
    },
    {
        name = "otter-overlords",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791948878/2D8D8AB3933F4C6BE46ACAD96630C57DBD8590C0/"
    },
    {
        name = "vagabond-arbiter",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791951841/1440B9EB1B17E9AB149FB33C5021C2E8C5011570/"
    },
    {
        name = "vagabond-ranger",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791952427/B40F2DD83339CD0ED68DAA3C2F41CBF9BD91CB8E/"
    },
    {
        name = "vagabond-scoundrel",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791953029/7DCC24CFA623ACE43EDD1954FAD8F783DB93387D/"
    },
    {
        name = "vagabond-thief",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791953784/6E08F3D2B7CFEB95266E45CDE4F0C131493260B5/"
    },
    {
        name = "vagabond-tinker",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791954051/9C922B7487C00B7AEDE95AA820905A5DDBBA62F4/"
    },
    {
        name = "vagabond-vagrant",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791954401/030AD078787CE0564E3B12D733EA03753702756E/"
    },
    {
        name = "vagabond-adventurer",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791951450/6330D3549A0FA4D9A6CEE27834DC59B3396D4BD6/"
    },
    {
        name = "vagabond-harrier",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791952096/F7EEAE9338B2AB0EF08BFC384C94B73853372BC1/"
    },
    {
        name = "vagabond-ronin",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791952743/CD494DB2E6CA7403A24B4F029DE4CF416FC04F0A/"
    },
    {
        name = "fangus-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791947898/4AC34C0FA07EAF3AE2660844292C08E2F42EC0EF/"
    },
    {
        name = "arachnid-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791945243/22BCFB3B63FDDC4F572A46303AC29F270B09E8A1/"
    },
    {
        name = "weekly-croak-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791946407/5683E8D3A4E0DA0F95A5B464208C5163963B9453/"
    },
    {
        name = "boars-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791945718/11ABA8E110D265F95B0EA6064B1072916E2578B0/"
    },
    {
        name = "trickster-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791950265/0FF759657E652C90E097D86D0ADC97C5684FEA92/"
    },
    {
        name = "learntoplay-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791948244/5BEA2423D3C33F23E78B95342D5D0893D777D61E/"
    },
    {
        name = "faction-title",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791955860/02D8E01A39FA04F5B87E22C0AAA36F58A77B72DC/"
    },
    {
        name = "bots-title",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791956953/48C620B5284463FDBE749B9DFA105230614FFB6D/"
    },
    {
        name = "scenarios-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791957287/1AFC52512FF2FA1DC6C04CE498BD968FFF599273/"
    },
    {
        name = "fan-factions-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791956594/578B293DAAC2DE414DAC0AA70FA7F93D05850232/"
    },
    {
        name = "fan-bots-button",
        url = "http://cloud-3.steamusercontent.com/ugc/792008966791956195/F40E6C3BF7213E4D5525ADA9C5451709D085E1AB/"
    },
}

function g()
    self.UI.setCustomAssets(UIASSETS)
    for x=1,10 do
        coroutine.yield()
    end

    self.UI.setXml(board_xml)
    -- We need some delay between setting ui and using it. hence the weird coroutine
    for x=1,10 do
        coroutine.yield()
    end
    showButtons()
    return 1
end

function onLoad(save_state)
    Global.call('ImHere', {self})
    startLuaCoroutine(self, 'g')
end

function toggleButtons(player, value, id)
    self.UI.setAttribute("subpanel", "active", "False")
    self.UI.setAttribute(id..'Buttons', 'active', value)
end

function setColor(_, color)
    local colors = Global.getTable('colors')
    if not colors[color] then
        for k,v in pairs(colors) do
            self.UI.setAttribute(k, 'active', v)
        end
        return
    end
    if chosen_faction == "Vagabond" then
        spawnWithColor(nil, color, true)
    else
        spawnWithColor(chosen_faction, color)
    end
end


function spawnFunction(player, faction, id, fan)
    local fan = fan or ''
    if isSpectator(player) then
        broadcastToColor("Sit down first", player.color, "Red")
        return
    end
    local avail = Global.getTable('available')
    local colors = Global.getTable('colors')
    if (avail[faction] < 1) then return end
    Global.call('FactionChosen', {faction})
    local preferred_color = ""
    if faction == "Vagabond" then
        preferred_color = "White"
    else
        preferred_color = EVERYTHING[fan..'factions'][faction].color
    end
    if not colors[preferred_color] then
        player.print("Preferred color for faction: "..faction.." alread taken.\nPlease pick another", red)
        if faction == "Vagabond" then
            chosen_faction = "Vagabond"
        else
            chosen_faction = EVERYTHING[fan..'factions'][faction].data
        end
        self.UI.setAttribute("factionsButtons", "active", "False")
        self.UI.setAttribute("botsButtons", "active", "False")
        self.UI.setAttribute("scenariosButtons", "active", "False")
        self.UI.setAttribute("rBotButtons", "active", "False")
        self.UI.setAttribute("fanButtons", "active", "False")
        self.UI.setAttribute("colorButtons", "active", "True")
        for k,v in pairs(colors) do
            self.UI.setAttribute(k, 'active', v)
        end
        return
    else
        if faction == "Vagabond" then
            spawnWithColor(nil, preferred_color, true)
        else
            spawnWithColor(EVERYTHING[fan..'factions'][faction].data, preferred_color)
        end
    end
end

function spawnFanFaction(player, faction, id)
    spawnFunction(player, faction, id, 'fan')
end

function isSpectator(player)
    if player.color == "Grey" then
        return true
    else
        return false
    end
end

function spawnWithColor(faction, color, vagabond)
    local colors = Global.getTable('colors')
    colors[color] = false
    Global.setTable('colors', colors)
    log(colors)
    local closest = findClosestPosition()
    closest.scale = {17.20, 5.40, 3.00}
    local val = false
    while not val do
        val = Player[color].setHandTransform(closest, 1)
    end
    if vagabond then
        self.UI.setAttribute("factionsButtons", "active", "False")
        self.UI.setAttribute("vagabondButtons", "active", "True")
        self.UI.setAttribute('typeToggles', "active", "False")
        self.UI.setAttribute("colorButtons", "active", "False")
    else
        spawnHere(faction)
    end
end

function spawnBot(player, faction, fan)
    if isSpectator(player) then
        broadcastToColor("Sit down first", player.color, "Red")
        return
    end
    local avail = Global.getTable('available')
    if (avail[faction:sub(5,-1)] < 1) then return end
    local colors = Global.getTable('colors')
    local bot = Global.getVar('bot')
    if not bot then
        bot_pieces = bot_stuff
        for _, v in ipairs(bot_pieces) do
            spawnObjectJSON({json=v})
        end
        Global.setVar('bot', true)
    end
    Global.call('FactionChosen', {faction:sub(5,-1)})
    local preferred_color = ""
    if fan then
        preferred_color = EVERYTHING['fanbots'][faction].color
    else
        preferred_color = EVERYTHING['officialbots'][faction].color
    end
    if not colors[preferred_color] then
        player.print("Preferred color for faction: "..faction.." alread taken.\nPlease pick another", red)
        if fan then
            chosen_faction = EVERYTHING['fanbots'][faction]
        else
            chosen_faction = EVERYTHING['officialbots'][faction]
        end
        self.UI.setAttribute("factionsButtons", "active", "False")
        self.UI.setAttribute("botsButtons", "active", "False")
        self.UI.setAttribute("scenariosButtons", "active", "False")
        self.UI.setAttribute("rBotButtons", "active", "False")
        self.UI.setAttribute("fanButtons", "active", "False")
        self.UI.setAttribute("colorButtons", "active", "True")
        for k,v in pairs(colors) do
            self.UI.setAttribute(k, 'active', v)
        end
        return
    else
        if fan then
            spawnWithColor(EVERYTHING['fanbots'][faction].data, preferred_color)
        else
            spawnWithColor(EVERYTHING['officialbots'][faction].data, preferred_color)
        end
    end
end

function spawnFanBot(player, faction)
    spawnBot(player, faction, true)
end

function spawnOfficialBot(player, faction)
    spawnBot(player, faction, false)
end

function spawnVagabond(player, vaga)
    if isSpectator(player) then
        broadcastToColor("Sit down first", player.color, "Red")
        return
    end
    avail = Global.getTable('available')
    if (avail[vaga] < 1) then return end
    Global.call('FactionChosen', {vaga})
    spawnHere(EVERYTHING['factions'][vaga].data)
end

function spawnScenario(player, scenario)
    if isSpectator(player) then
        broadcastToColor("Sit down first", player.color, "Red")
        return
    end
    spawnHere(EVERYTHING['scenarios'][scenario].data)
end

function showButtons()
    local avail = Global.getTable('available')
    for _, k in ipairs(buttons) do
        local set = false
        if (k:sub(1,-2)..tostring(avail[k:sub(1,-2)] or 0)  == k) or (k:sub(5,-2)..tostring(avail[k:sub(5,-2)] or 0) == k:sub(5,-1)) or (avail[k] and avail[k] > 0) then
            self.UI.setAttribute(k, 'active', true)
        else
            self.UI.setAttribute(k, 'active', false)
        end
    end
end

function deleteThis()
    Global.call('ImGone', {self})
    self.destruct()
end

function spawnHere(to_spawn)
    local my_rot = self.getRotation()
    local scale = self.getScale()

    scale.x = 1/scale.x
    scale.z = 1/scale.z

    for _,v in ipairs(to_spawn) do
        local new_pos = self.positionToWorld(Vector(v.move_to) * scale)
        spawnObjectJSON({
            json              = v.json,
            position          = new_pos,
            callback_function = function(o) o.setRotation({o.getRotation().x, o.getRotation().y+my_rot.y, o.getRotation().z}) end
        })
    end
    Global.call('ImGone', {self})
    self.destruct()
end

function findClosestPosition()
    local own_pos = self.getPosition()
    local closest = nil
    local smallest_distance = 100000000
    local places = {{position={-50.00, 5.00, -64.50}, rotation={0, 0, 0}}, {position={0.00, 5.00, -64.50},  rotation={0, 0, 0}}, {position={50.00, 5.00, -64.50},  rotation={0, 0, 0}}, {position={50.00, 5.00, 64.50},  rotation={0.00, 180.00, 0.00}}, {position={0.00, 5.00, 64.50},  rotation={0.00, 180.00, 0.00}}, {position={-50.00, 5.00, 64.50},  rotation={0.00, 180.00, 0.00}}}
    for _, place in ipairs(places) do
        pos = place.position
        local distance = math.sqrt(math.pow(own_pos.x-pos[1], 2)+math.pow(own_pos.z-pos[3], 2))
        if distance < smallest_distance then
            smallest_distance = distance
            closest = place
        end
    end
    return closest
end

function none() end
